### PR TITLE
Deployable ACLs

### PR DESCRIPTION
**Pull request by jardleex**
Hello @mrlesmithjr 

this PR comes via #49 and will allow the role user to define Consul ACLs with this role. This provides a simple, central, easy and reproducible way of defining ACLs for Consul. This attempt would be far saver then setting ACLs via WebGUI as this would not be reproducible at any time.

This PR utilizes [consul_acl](https://docs.ansible.com/ansible/latest/consul_acl_module.html).

Let me know what you think or you'd like to have something changed on it.

Best

Jard

### CODE REVIEW

**Comment by jardleex** [comment]
Hello @mrlesmithjr 

Do you have questions on that or something you'd like to have improved on this one?

As we're making good progress with our Consul deployment I'd like to get this in to have solid way of deploying ACL rules.

**Comment by mrlesmithjr** [comment]
@jardleex Are we still good to merge this one?

**Comment by jardleex** [comment]
@mrlesmithjr,

yes, as there are no conflicts marked we are good to go.

**Comment by mrlesmithjr** [comment]
@jardleex Merged!!!

**Comment by jardleex** [comment]
Thanks for merging!
That's a huge improvement to the role.

**Comment by jardleex** [comment]
Please note that there is an open issue in for Ansible <2.4 which effects this change:

https://github.com/ansible/ansible/issues/30557

So at least Ansible 2.4 is required to work properly or the consul_acl module have to be updated out of order. 
We did the later one as we can't update to Ansible 2.4 due to another issue in 2.4

**Pull request merged**
